using System.Collections;using System.Collections.Generic;using UnityEngine;
public class ChunkWarsPrototype:MonoBehaviour{
 public static ChunkWarsPrototype I;public readonly List<Chunk> chunks=new();
 [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]static void Boot(){if(!FindObjectOfType<ChunkWarsPrototype>())new GameObject("CHUNK_WARS").AddComponent<ChunkWarsPrototype>();}
 void Awake(){I=this;RenderSettings.ambientLight=new Color(.24f,.25f,.32f);var sun=new GameObject("Sun").AddComponent<Light>();sun.type=LightType.Directional;sun.intensity=1.1f;sun.transform.rotation=Quaternion.Euler(48,-32,0);World();Player();}
 Material M(Color c){var m=new Material(Shader.Find("Standard"));m.color=c;return m;}
 GameObject Cube(string n,Vector3 p,Vector3 s,Color c){var g=GameObject.CreatePrimitive(PrimitiveType.Cube);g.name=n;g.transform.position=p;g.transform.localScale=s;g.GetComponent<Renderer>().material=M(c);return g;}
 void World(){Cube("World",Vector3.down,new Vector3(154,2,154),new Color(.07f,.085f,.1f));for(int x=-2;x<=2;x++)for(int z=-2;z<=2;z++){var c=new Vector3(x*30,0,z*30);var root=new GameObject($"Chunk_{x}_{z}");root.transform.position=c;var ch=root.AddComponent<Chunk>();ch.grid=new Vector2Int(x,z);ch.owner=x==0&&z==0?"PLAYER":(x+z)%3==0?"RIVALS":"WILD";chunks.Add(ch);Cube("Floor",c+Vector3.up*.03f,new Vector3(28,.08f,28),new Color(.16f+Mathf.Abs(x%2)*.04f,.18f,.22f)).transform.SetParent(root.transform);ch.point=Cube("ControlPoint",c+Vector3.up*2.2f,new Vector3(1.2f,4.4f,1.2f),ch.owner=="PLAYER"?Color.green:ch.owner=="WILD"?Color.gray:Color.red);ch.point.transform.SetParent(root.transform);Nodes(root.transform,c,x,z);if((x+z)%2==0)Cube("Workshop / Market",c+new Vector3(-7,2.2f,7),new Vector3(7,4.4f,5),new Color(.18f,.2f,.28f)).transform.SetParent(root.transform);if(ch.owner=="RIVALS")Dummy(c+new Vector3(5,1,5));}}
 void Nodes(Transform root,Vector3 c,int x,int z){string[] a={"Wood","Stone","Gold","Diamond"};for(int i=0;i<5;i++){string t=a[Mathf.Abs(x*7+z*3+i)%4];var g=GameObject.CreatePrimitive(t=="Wood"?PrimitiveType.Cylinder:PrimitiveType.Sphere);g.name=t;g.transform.SetParent(root);g.transform.position=c+new Vector3(-10+i*5,t=="Wood"?1.5f:.7f,-9+(i*7)%18);g.transform.localScale=t=="Wood"?new Vector3(.8f,1.5f,.8f):Vector3.one*(t=="Diamond"?.75f:1.2f);g.GetComponent<Renderer>().material=M(t=="Wood"?new Color(.35f,.18f,.06f):t=="Stone"?Color.gray:t=="Gold"?new Color(1,.65f,.05f):Color.cyan);var n=g.AddComponent<Node>();n.type=t;n.amount=t=="Diamond"?1:t=="Gold"?2:5;}}
 void Dummy(Vector3 p){var g=GameObject.CreatePrimitive(PrimitiveType.Capsule);g.name="Raid Defender";g.transform.position=p;g.GetComponent<Renderer>().material=M(new Color(.7f,.12f,.16f));g.AddComponent<Dummy>();}
 void Player(){var p=new GameObject("Player");p.transform.position=new Vector3(0,2,10);var cc=p.AddComponent<CharacterController>();cc.height=1.8f;cc.radius=.35f;var pc=p.AddComponent<FPS>();var cam=new GameObject("Camera").AddComponent<Camera>();cam.transform.SetParent(p.transform);cam.transform.localPosition=new Vector3(0,.7f,0);cam.tag="MainCamera";pc.cam=cam;p.AddComponent<Game>();}}
public class FPS:MonoBehaviour{public Camera cam;CharacterController cc;float pitch,vy;void Start(){cc=GetComponent<CharacterController>();Cursor.lockState=CursorLockMode.Locked;}void Update(){if(Input.GetKeyDown(KeyCode.Escape))Cursor.lockState=CursorLockMode.None;if(Input.GetMouseButtonDown(0))Cursor.lockState=CursorLockMode.Locked;if(Cursor.lockState==CursorLockMode.Locked){transform.Rotate(0,Input.GetAxis("Mouse X")*2.2f,0);pitch=Mathf.Clamp(pitch-Input.GetAxis("Mouse Y")*2.2f,-85,85);cam.transform.localRotation=Quaternion.Euler(pitch,0,0);}var m=transform.right*Input.GetAxis("Horizontal")+transform.forward*Input.GetAxis("Vertical");float s=Input.GetKey(KeyCode.LeftShift)?10:6;if(cc.isGrounded){vy=-2;if(Input.GetKeyDown(KeyCode.Space))vy=7;}vy+=Physics.gravity.y*Time.deltaTime;m.y=vy;cc.Move(m*s*Time.deltaTime);}}
public class Node:MonoBehaviour{public string type;public int amount;bool ready=true;public void Take(Game g){if(!ready)return;g.Add(type,amount*(g.pick?2:1));ready=false;gameObject.SetActive(false);StartCoroutine(Back());}IEnumerator Back(){yield return new WaitForSeconds(12);ready=true;gameObject.SetActive(true);}}
public class Dummy:MonoBehaviour{int hp=100;Vector3 spawn;void Start(){spawn=transform.position;}public void Hit(int d){hp-=d;if(hp<=0)StartCoroutine(Back());}IEnumerator Back(){gameObject.SetActive(false);yield return new WaitForSeconds(7);hp=100;transform.position=spawn;gameObject.SetActive(true);}}
public class Chunk:MonoBehaviour{public Vector2Int grid;public string owner;public GameObject point;public bool raid;public float capture;public void Own(){owner="PLAYER";point.GetComponent<Renderer>().material.color=Color.green;}}
public class Game:MonoBehaviour{public int wood,stone,gold,diamond,money=500,ammo=90,hits;public bool pick;FPS pc;Chunk current;string note="Добро пожаловать в Войну Чанков";float until;void Start(){pc=GetComponent<FPS>();}public void Add(string t,int n){if(t=="Wood")wood+=n;if(t=="Stone")stone+=n;if(t=="Gold")gold+=n;if(t=="Diamond")diamond+=n;Say($"Получено: {t} +{n}");}void Say(string s){note=s;until=Time.time+3;}
 void Update(){current=ChunkWarsPrototype.I.chunks.Find(c=>Mathf.Abs(transform.position.x-c.transform.position.x)<15&&Mathf.Abs(transform.position.z-c.transform.position.z)<15);if(Input.GetKeyDown(KeyCode.E)&&Physics.Raycast(pc.cam.transform.position,pc.cam.transform.forward,out RaycastHit h,4)){var n=h.collider.GetComponent<Node>();if(n)n.Take(this);}if(Input.GetMouseButtonDown(0)&&Cursor.lockState==CursorLockMode.Locked&&ammo>0){ammo--;if(Physics.Raycast(pc.cam.transform.position,pc.cam.transform.forward,out RaycastHit s,120)){var d=s.collider.GetComponent<Dummy>();if(d){d.Hit(34);hits++;Say("Попадание");}}}if(Input.GetKeyDown(KeyCode.C)){if(!pick&&wood>=20&&stone>=20){wood-=20;stone-=20;pick=true;Say("Кирка улучшена");}else Say("Нужно 20 дерева и камня");}if(Input.GetKeyDown(KeyCode.B)){if(wood>=5&&stone>=5){wood-=5;stone-=5;ammo+=30;Say("+30 патронов");}}if(Input.GetKeyDown(KeyCode.T)){int v=wood*2+stone*3+gold*20+diamond*80;money+=v;wood=stone=gold=diamond=0;Say($"Продано на ${v}");}if(Input.GetKeyDown(KeyCode.R)&&current!=null&&!current.raid&&current.owner!="PLAYER")StartCoroutine(Raid(current));if(current!=null&&current.raid&&Vector3.Distance(transform.position,current.point.transform.position)<5){current.capture+=Time.deltaTime;if(current.capture>=10){current.raid=false;current.Own();money+=1000;Say("ЧАНК ЗАХВАЧЕН! +$1000");}}}
 IEnumerator Raid(Chunk c){c.raid=true;c.capture=0;Say("Подготовка к рейду: 5 секунд");yield return new WaitForSeconds(5);Say("Удерживайте контрольную точку");}
 void OnGUI(){GUI.color=new Color(0,0,0,.75f);GUI.Box(new Rect(15,15,405,170),"");GUI.color=Color.white;GUI.Label(new Rect(30,25,380,24),"ВОЙНА ЧАНКОВ — PLAYABLE PROTOTYPE");GUI.Label(new Rect(30,52,380,24),$"Дерево {wood}  Камень {stone}  Золото {gold}  Алмазы {diamond}");GUI.Label(new Rect(30,78,380,24),$"${money} | Патроны {ammo} | Попадания {hits}");GUI.Label(new Rect(30,104,380,24),current==null?"Вне карты":$"Чанк {current.grid} | {current.owner}"+(current.raid?$" | Захват {current.capture:0}/10":""));GUI.Label(new Rect(30,132,380,44),"E добыть | ЛКМ огонь | C кирка | B патроны\nT продать | R рейд | Shift бег");if(Time.time<until){GUI.color=new Color(.45f,.15f,.75f,.92f);GUI.Box(new Rect(Screen.width/2-190,35,380,42),note);}GUI.color=Color.white;GUI.Label(new Rect(Screen.width/2-4,Screen.height/2-12,20,20),"+");}}
